### ISSUE TITLE
Unknown CMake command: sofa_create_package_with_targets 

### ISSUE THREAD

**Issue by Pempafugue** [SofaDefrost/STLIB#49]
Hello,
I am trying to follow these steps https://github.com/sofa-framework/SofaROSConnector to connect Sofa v20.06 and ROS noetic. During the cmake-gui Configuration, this error occurs:
CMake Error at applications/plugins/STLIB/CMakeLists.txt:42 (sofa_create_package_with_targets):
  Unknown CMake command "sofa_create_package_with_targets".

I am using Ubuntu 20.04
Thanks for your help!

**Comment by clausagerskov** [comment]
Same problem here on 18.04, SOFA version v20.06.01

**Comment by damienmarchal** [comment]
Hi @Pempafugue, hi @clausagerskov,

Thanks for taking time to report the error. 

As far as I can see, sofa_create_package_with_target is a macro that I introduced two month ago to be in sync with the recent evolution of the master branch of SOFA. From what I can see in the SOFA repository at tag v20.06.01 sofa_create_package_with_targets wasn't there at release time and was not backported. 

My suggestion is either to make a full sofa build using the sofa master branch + STLIB or try to find a commit in STLIB history that is working with v20.06.01. Actually it makes me think that  we probably we should tag each of our project at each sofa release... too much to do, not enough man(and woman)- power.

**Comment by Pempafugue** [comment]
Thanks for your answer! I'll try your suggestions
Good luck for all the work!

**Comment by damienmarchal** [comment]
Just quick remark about ROS...there is also a very simple way to connect SoftRobots using pyros (instead of the SofaRosConnector). An example is provided in the SoftRobots directory.

**Comment by Pempafugue** [comment]
I am gonna check this out! thanks for the advice
