### ISSUE TITLE
CMake file gives configuration errors

### ISSUE THREAD

**Issue by AboudFayad** [SofaDefrost/STLIB#6]
I am trying to build the library using cmake on windows, but I get the following error every time  I try to:
`cmake
CMake Error at CMakeLists.txt:19 (sofa_set_python_directory):
  Unknown CMake command "sofa_set_python_directory".
`
I tried adding the SofaMacros.cmake, but with no luck.

**Comment by damienmarchal** [comment]
Hi Aboud,

Thanks for your question. 

STLIB is a library that rely on the SofaPython plugin so you need to activate this plugin for the library to work. If you don't know how to compile Sofa or its plugins you can join us on our chat room at:
https://gitter.im/sofa-framework/sofa
