### ISSUE TITLE
[running error] with stlib.pyscn

### ISSUE THREAD

**Issue by MingshanHe** [SofaDefrost/STLIB#85]
Dear,
When I run the `./runsofa` with the `stlib.pyscn` I have the error in my terminal as follows.
![image](https://user-images.githubusercontent.com/56861752/177133578-7c47777a-9428-414a-97b5-9f9b5c29f121.png)
And I have download the `STLIB` and compile it successfully.
When I run the `./runsofa`, the plugin will be loaded automosly.
And I would like to inquire what's wrong with this.
![image](https://user-images.githubusercontent.com/56861752/177133835-7c63621c-37dd-45d2-a08f-048ecd350af9.png)

Best regards,
Beal

**Comment by damienmarchal** [comment]
Hi @MingshanHe,

Thanks for reporting this issue. 

What is wrong is that we didn't updated this stlib.pyscn file and it is now outdated as the stlib is now in version 3. This file is just an example and it should have no consequence on using sofa, softrobots or stlib. 

With the help of your report that we will update the file for the next release v22.06 which should be release this week or the week after. 

So thanks again for reporting the issue.

**Comment by MingshanHe** [comment]
Thanks for your answer!
Good luck with the work!
